### PR TITLE
Zabbix Host title added

### PR DESCRIPTION
**Pull request by JXGA**
Hello, 

I made a slight adjustment to allow the host-name of the receiving 'host' on Zabbix to be specified. Zabbix-Sender can then send it to any hostname inside Zabbix. 

Thanks!

### CODE REVIEW

**Comment by okand** [comment]
Been a long while since I last looked at this as I don't work with zabbix daily anymore but if I recall correctly this was just based on the name of the file it all read the domains from before. Thus you could just make a new file with the name of the host you want the data to be filed under once sent to zabbix.

**Comment by JXGA** [comment]
I missed this!

I guess the only addition my PR brings then is the ability to run different domains and be able to send them to any zabbix host. Previously I was limited to reading one domain file per zab. host, which isn’t the end of the world!

**Comment by okand** [comment]
In a previous life I had the crontab written like this:

```
20 12 * * * zabbix-whois-discovery.py customer.one.website.monitor.host
30 12 * * * zabbix-whois-check.py customer.one.website.monitor.host
22 12 * * * zabbix-whois-discovery.py customer.two.website.monitor.host
32 12 * * * zabbix-whois-check.py customer.two.website.monitor.host
```

And files named `customer.one.website.monitor.host.json` and `customer.two.website.monitor.host.json`

These website monitor hosts were then just “dummy hosts” available at 127.0.0.1 on the zabbix server itself that also ran these scripts but they can just as well be a real monitored host somewhere if you want the checks data to be filed there instead of in a single spot for all domains. Zabbix only cares about what you claim the name is in the data you send in with zabbix_sender, not if the source IP matches.

Zabbix has both the hostname and visible hostname fields when configuring a host so you can have its name easily displayed with spaces but referenced for the script without them.

**Comment by okand** [comment]
I'm just gonna close this without merging but thank you for your contribution anyway.

I'm happy that others actually found these scripts useful :)

**Pull request closed without merging**
